---
title: "Coffee Review Preliminary Results"
author: "Xin Wang"
date: "2025-03-13"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv(LANG = "en")
```

```{r}
library(tidyverse)
```

# Load data

```{r}
data <- read.csv("../data/coffee_reviews_parsed.csv") 
```

# Data processing

## Roast Level

- Replace "" with NA

- Convert roast level into an ordinal variable

```{r}
unique(data$Roast.Level)
```


```{r Manipulate Roast Level column}
# Replace empty strings with NA
data$Roast.Level[data$Roast.Level == ""] <- NA

# Convert to an ordered factor (ensure column name is correct)
data$Roast.Level <- factor(
  data$Roast.Level, 
  levels = c("Light", "Medium-Light", "Medium", "Medium-Dark", "Dark", "Very Dark"), 
  ordered = TRUE
)
```

## Deal with Agtron column
```{r}
# Check if every cell follows "1/1" pattern
data <- data |>
  mutate(agtron_is_valid_format = grepl("^\\d+/\\d+$", Agtron)) 

data |>
  filter(agtron_is_valid_format == FALSE)
```

```{r warning=FALSE}
df <- data |>
  separate(Agtron, into = c("Agtron_whole", "Agtron_ground"), sep="/") |>
  mutate(
    Agtron_whole = as.numeric(Agtron_whole),
    Agtron_ground = as.numeric(Agtron_ground)
  )
```



# EDA
## Bar plots - 1 variable

```{r}
png("../figures/roast_level_distribution.png", width=1500, height=1000, res=256)
# data |>
#   filter(!is.na(Roast.Level)) |>
#   ggplot(aes(x=Roast.Level)) +
#   geom_bar() + 
#   labs(
#     x = "Coffee Roast Level",
#     y = "Coffee Count",
#     title = "Most coffee is medium-light roasted."
#   )

# 1. Calculate the frequency
value_counts <- table(data$Roast.Level)
# print(value_counts)

# 2. Convert the table into a data frame
value_counts_df <- as.data.frame(value_counts)

# 3. Create the bar plot
ggplot(value_counts_df, aes(x = Var1, y = Freq)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = Freq), vjust = -0.5) +
  labs(
    x = "Coffee Roast Level", 
    y = "Coffee Count", 
    title = "Most coffee is medium-light roasted.")
```

## Roast level vs Rating
```{r}
df |>
  filter(!is.na(data$Roast.Level)) |>
  ggplot(aes(x = Roast.Level, y = Rating)) + 
  geom_boxplot(na.rm=TRUE) + 
  labs(
    x = "Roast Level",
    y = "Overall Rating",
    title = "Lighter roast level tends to get a higher rating."
  )
```


